### ISSUE TITLE
Downloading the Wrong Images

### ISSUE THREAD

**Issue by MrWeeb69** [9-FS/nhentai_archivist#35] opened 2024-10-08 08:00 UTC
was archiving my favourites and i noticed the errors i was getting were strange. it was requesting the correct id to download but when it started to download it was downloading a completely different one that wasn't valid. not sure if this is a program issue or a server issue 😥

Log: https://gist.githubusercontent.com/MrWeeb69/0c509e592d615be962f2109acd28c3f0/raw/2aecc3c18cc185acf742c16cf9c791947ab0f979/gistfile1.txt

**Comment by MrWeeb69** [comment] 2024-10-08 08:09
i'd like to add that it was working fine 40 min ago and any id i try ends up with the same result of downloading a completely different number then what i inputed

**Comment by 9-FS** [comment] 2024-10-08 08:57
Duplicate of #33 and #34?

**Closed** 2024-10-13 14:13 UTC
