### ISSUE TITLE
Feature Request: Put files in subfolder instead of cbz archive for easier post download deduplicating

### ISSUE THREAD

**Issue by deathoftheages** [9-FS/nhentai_archivist#12] opened 2024-09-15 19:42 UTC
Hey, I have been using your program since you posted it on reddit.  I hope it's ok to request a feature here.  The only issue I have had once you helped me figure out how to use nHA is the sheer amount of duplicates.  I don't program, so I have no idea how hard it would be to have the program figure out which images are dupes before downloading them, but I have a feeling that would be a huge headache to implement.  

I have the idea for what I think would be an easier workaround on your end.  If you could make it, so there is a flag(I don't know the correct term) in the .env file so we could choose not to have the images put in a cbz file.  Instead have it put each comic into its own subfolder along with the cbz xml file.  What this would do is make it easy just to use a 3rd party duplicate file finder to scan the subfolders and delete the dupes.

Sure, you would still have to download the dupes, but it then becomes trivial to find and delete them.  Sure it won't delete the xml files for the dupe folders, but once the pics are gone it is as simpler as sorting the folders by size and deleting the tiny ones.  Then it would just be figuring out a way to batch making cbz files out of those subfolders after the de-duping.

This is just a thought.  I know nothing about programming, so this might be something that isn't easy to do for your program or hell you might not feel like adding this kind of feature.  Either way, I want to thank you for releasing it for free for everyone else.  You didn't have to, but you made a lot of people's lives a lot easier in doing so.

**Comment by 9-FS** [comment] 2024-09-15 21:40
Thank you for your idea. :) This is a duplicate of issue #2 though, I'll have to ask you to please copy and paste your message there so we can keep all ideas regarding deduplication together at 1 place, thank you.

**Closed** 2024-09-15 21:40 UTC
